<?php
declare(strict_types=1);
require_once __DIR__ . '/../Briefing/lib.php';

$conn=briefing_conn(); $body=briefing_body(); $action=(string)($body['action']??$_GET['action']??'');
if($action==='')briefing_json(['ok'=>false,'message'=>'Ação obrigatória.'],400);

function ext_session(mysqli $conn, bool $mutation=false): array { return briefing_external_session($conn,$mutation); }
function ext_question(mysqli $conn,int $briefingId,int $questionId):?array{$stmt=briefing_stmt($conn,'SELECT q.* FROM briefing_question q JOIN briefing_section s ON s.id=q.briefing_section_id WHERE q.id=? AND s.briefing_id=? AND s.ativa=1 AND q.ativa=1','ii',[$questionId,$briefingId]);$q=$stmt->get_result()->fetch_assoc();$stmt->close();return $q?:null;}
function ext_create_session(mysqli $conn,int $briefingId,int $participantId):array{$token=bin2hex(random_bytes(32));$csrf=bin2hex(random_bytes(32));$exp=time()+8*3600;$stmt=briefing_stmt($conn,'INSERT INTO briefing_external_session (briefing_id,participant_id,token_hash,csrf_hash,expira_em,ultimo_acesso_em) VALUES (?,?,?,?,FROM_UNIXTIME(?),UTC_TIMESTAMP())','iissi',[$briefingId,$participantId,hash('sha256',$token),hash('sha256',$csrf),$exp]);$stmt->close();briefing_set_ext_cookie($token,$exp);return ['csrf'=>$csrf,'expires_at'=>gmdate('c',$exp)];}

try {
    if($action==='start'){
        $token=(string)($body['token']??'');$email=briefing_email($body['email']??'');$name=briefing_clean_text($body['name']??'',180);if(strlen($token)!==64)throw new InvalidArgumentException('Link inválido.');
        if(!briefing_rate_limit($conn,'otp:start:'.($_SERVER['REMOTE_ADDR']??'').':'.$email,5,600))briefing_json(['ok'=>false,'message'=>'Muitas tentativas. Aguarde alguns minutos.'],429);
        $link=briefing_external_link($conn,$token);if(!$link)briefing_json(['ok'=>false,'message'=>'Este link expirou ou foi revogado.'],404);
        $contact=briefing_contact_by_email($conn,(int)$link['obra_id'],$email);$participantId=(int)briefing_scalar($conn,'SELECT id FROM briefing_participant WHERE briefing_id=? AND email=? AND ativo=1','is',[(int)$link['briefing_id'],$email]);
        if($participantId<=0){if($name==='')$name=$contact['nome']??'';if($name==='')briefing_json(['ok'=>false,'message'=>'Informe seu nome para continuar.'],422);$cid=$contact['idcontato_cliente']??null;$company=$contact['nome_cliente']??null;$stmt=briefing_stmt($conn,'INSERT INTO briefing_participant (briefing_id,contato_cliente_id,email,nome,empresa) VALUES (?,?,?,?,?)','iisss',[(int)$link['briefing_id'],$cid,$email,$name,$company]);$participantId=(int)$conn->insert_id;$stmt->close();}
        $briefing=briefing_fetch($conn,(int)$link['briefing_id'],true);$code=(string)random_int(100000,999999);if(!briefing_send_otp($email,$code,(string)$briefing['titulo']))briefing_json(['ok'=>false,'message'=>'O envio do código por e-mail não está configurado.'],503);
        $conn->begin_transaction();briefing_stmt($conn,'UPDATE briefing_otp_challenge SET expira_em=UTC_TIMESTAMP() WHERE access_link_id=? AND email=? AND verificado_em IS NULL','is',[(int)$link['id'],$email])->close();$stmt=briefing_stmt($conn,'INSERT INTO briefing_otp_challenge (access_link_id,participant_id,email,code_hash,expira_em) VALUES (?,?,?,?,DATE_ADD(UTC_TIMESTAMP(), INTERVAL 10 MINUTE))','iiss',[(int)$link['id'],$participantId,$email,hash('sha256',$code)]);$stmt->close();briefing_event($conn,(int)$link['briefing_id'],'otp.requested','PARTICIPANTE',$participantId);$conn->commit();briefing_json(['ok'=>true,'message'=>'Seus dados foram recebidos. Enviamos um código de acesso para seu e-mail.']);
    }
    if($action==='verify'){
        $token=(string)($body['token']??'');$email=briefing_email($body['email']??'');$code=preg_replace('/\D/','',(string)($body['code']??''));if(strlen($token)!==64||strlen($code)!==6)throw new InvalidArgumentException('Código inválido.');
        if(!briefing_rate_limit($conn,'otp:verify:'.($_SERVER['REMOTE_ADDR']??'').':'.$email,5,600))briefing_json(['ok'=>false,'message'=>'Muitas tentativas. Aguarde alguns minutos.'],429);
        $link=briefing_external_link($conn,$token);if(!$link)briefing_json(['ok'=>false,'message'=>'Este link expirou ou foi revogado.'],404);$stmt=briefing_stmt($conn,'SELECT * FROM briefing_otp_challenge WHERE access_link_id=? AND email=? AND verificado_em IS NULL AND expira_em>UTC_TIMESTAMP() ORDER BY id DESC LIMIT 1','is',[(int)$link['id'],$email]);$challenge=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$challenge)briefing_json(['ok'=>false,'message'=>'Solicite um novo código.'],422);if((int)$challenge['tentativas']>=5)briefing_json(['ok'=>false,'message'=>'Limite de tentativas atingido. Solicite outro código.'],429);
        if(!hash_equals($challenge['code_hash'],hash('sha256',$code))){briefing_stmt($conn,'UPDATE briefing_otp_challenge SET tentativas=tentativas+1 WHERE id=?','i',[(int)$challenge['id']])->close();briefing_json(['ok'=>false,'message'=>'Código inválido.'],422);}
        $conn->begin_transaction();briefing_stmt($conn,'UPDATE briefing_otp_challenge SET verificado_em=UTC_TIMESTAMP() WHERE id=?','i',[(int)$challenge['id']])->close();briefing_stmt($conn,'UPDATE briefing_participant SET verificado_em=COALESCE(verificado_em,UTC_TIMESTAMP()),ultimo_acesso_em=UTC_TIMESTAMP(),ultima_atividade_em=UTC_TIMESTAMP() WHERE id=?','i',[(int)$challenge['participant_id']])->close();briefing_stmt($conn,'UPDATE briefing_access_link SET ultimo_uso_em=UTC_TIMESTAMP() WHERE id=?','i',[(int)$link['id']])->close();briefing_event($conn,(int)$link['briefing_id'],'participant.verified','PARTICIPANTE',(int)$challenge['participant_id']);$session=ext_create_session($conn,(int)$link['briefing_id'],(int)$challenge['participant_id']);$conn->commit();briefing_publish_realtime((int)$link['briefing_id'],'participant.presence_changed');briefing_json(['ok'=>true]+$session);
    }
    $mutating=in_array($action,['answer.save','briefing.submit','comment.save','ws.ticket'],true);$session=ext_session($conn,$mutating);$briefingId=(int)$session['briefing_id'];$participantId=(int)$session['participant_id'];
    if($action==='bootstrap'){
        if($session['status']==='AGUARDANDO_CLIENTE'){briefing_stmt($conn,"UPDATE briefing_online SET status='EM_PREENCHIMENTO' WHERE id=? AND status='AGUARDANDO_CLIENTE'",'i',[$briefingId])->close();briefing_event($conn,$briefingId,'briefing.started','PARTICIPANTE',$participantId);briefing_publish_realtime($briefingId,'briefing.status_updated',['status'=>'EM_PREENCHIMENTO']);}
        briefing_stmt($conn,'UPDATE briefing_participant SET ultimo_acesso_em=UTC_TIMESTAMP(),ultima_atividade_em=UTC_TIMESTAMP() WHERE id=?','i',[$participantId])->close();$briefing=briefing_fetch($conn,$briefingId,true);briefing_json(['ok'=>true,'csrf'=>null,'participant'=>['name'=>$session['nome'],'email'=>$session['email']],'briefing'=>$briefing]);
    }
    if($action==='answer.save'){
        if(!in_array($session['status'],BRIEFING_OPEN_STATUSES,true))briefing_json(['ok'=>false,'message'=>'Este briefing não está disponível para edição.'],409);$questionId=(int)($body['question_id']??0);$expected=(int)($body['expected_version']??-1);$operation=(string)($body['operation_uuid']??'');if(!preg_match('/^[0-9a-f-]{36}$/i',$operation))throw new InvalidArgumentException('Identificador de operação inválido.');$question=ext_question($conn,$briefingId,$questionId);if(!$question)throw new InvalidArgumentException('Pergunta inválida.');$notApplicable=(bool)($body['not_applicable']??false);$value=briefing_valid_answer($question,$body['value']??null,$notApplicable);$encoded=$value===null?null:json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
        $conn->begin_transaction();$previous=briefing_scalar($conn,'SELECT resultado_json FROM briefing_answer_operation WHERE briefing_id=? AND operacao_uuid=?','is',[$briefingId,$operation]);if($previous!==null){$conn->commit();briefing_json(['ok'=>true,'idempotent'=>true,'answer'=>briefing_json_decode($previous)]);}
        $stmt=briefing_stmt($conn,'SELECT * FROM briefing_answer WHERE briefing_question_id=? FOR UPDATE','i',[$questionId]);$answer=$stmt->get_result()->fetch_assoc();$stmt->close();
        if($answer && (int)$answer['versao']!==$expected){$conn->rollback();briefing_json(['ok'=>false,'message'=>'A resposta foi alterada por outra pessoa.','conflict'=>['value'=>briefing_json_decode($answer['valor_json']),'not_applicable'=>(bool)$answer['nao_aplica'],'version'=>(int)$answer['versao'],'updated_at'=>$answer['atualizado_em']]],409);}
        if(!$answer){if($expected!==0){$conn->rollback();briefing_json(['ok'=>false,'message'=>'A resposta foi alterada por outra pessoa.','conflict'=>['version'=>0]],409);}$stmt=briefing_stmt($conn,'INSERT INTO briefing_answer (briefing_question_id,valor_json,nao_aplica,versao,respondido_por_participant_id,respondido_em,atualizado_por_participant_id) VALUES (?,?,?,1,?,UTC_TIMESTAMP(),?)','isiii',[$questionId,$encoded,(int)$notApplicable,$participantId,$participantId]);$answerId=(int)$conn->insert_id;$version=1;$before=null;$stmt->close();}
        else {$answerId=(int)$answer['id'];$version=(int)$answer['versao']+1;$before=$answer['valor_json'];$stmt=briefing_stmt($conn,'UPDATE briefing_answer SET valor_json=?,nao_aplica=?,versao=?,atualizado_por_participant_id=?,atualizado_em=UTC_TIMESTAMP() WHERE id=? AND versao=?','siiiii',[$encoded,(int)$notApplicable,$version,$participantId,$answerId,$expected]);if($stmt->affected_rows!==1){$stmt->close();$conn->rollback();briefing_json(['ok'=>false,'message'=>'Conflito de versão.'],409);}$stmt->close();}
        $open=briefing_scalar($conn,"SELECT id FROM briefing_answer_edit_session WHERE answer_id=? AND participant_id=? AND fechado_em IS NULL AND ultimo_salvamento_em>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 SECOND) ORDER BY id DESC LIMIT 1",'ii',[$answerId,$participantId]);if($open){briefing_stmt($conn,'UPDATE briefing_answer_edit_session SET depois_json=?,ultimo_salvamento_em=UTC_TIMESTAMP() WHERE id=?','si',[$encoded,(int)$open])->close();}else{briefing_stmt($conn,'INSERT INTO briefing_answer_edit_session (answer_id,participant_id,antes_json,depois_json) VALUES (?,?,?,?)','iiss',[$answerId,$participantId,$before,$encoded])->close();}
        briefing_stmt($conn,"UPDATE briefing_question_request SET status='RESPONDIDO_AGUARDANDO_CONFERENCIA',respondido_em=UTC_TIMESTAMP() WHERE briefing_question_id=? AND status='SOLICITADO'",'i',[$questionId])->close();$result=['id'=>$answerId,'value'=>$value,'not_applicable'=>$notApplicable,'version'=>$version];briefing_stmt($conn,'INSERT INTO briefing_answer_operation (briefing_id,operacao_uuid,answer_id,resultado_json) VALUES (?,?,?,?)','isis',[$briefingId,$operation,$answerId,json_encode($result,JSON_UNESCAPED_UNICODE)] )->close();briefing_stmt($conn,'UPDATE briefing_participant SET ultima_atividade_em=UTC_TIMESTAMP() WHERE id=?','i',[$participantId])->close();briefing_event($conn,$briefingId,'answer.updated','PARTICIPANTE',$participantId,['question_id'=>$questionId,'version'=>$version]);$conn->commit();briefing_publish_realtime($briefingId,'answer.updated',['question_id'=>$questionId,'version'=>$version,'participant_id'=>$participantId]);briefing_json(['ok'=>true,'answer'=>$result,'progress'=>briefing_progress($conn,$briefingId)]);
    }
    if($action==='briefing.submit'){
        if(!in_array($session['status'],BRIEFING_OPEN_STATUSES,true))throw new InvalidArgumentException('Este briefing não está disponível para envio.');$missing=(int)briefing_scalar($conn,"SELECT COUNT(*) FROM briefing_question q JOIN briefing_section s ON s.id=q.briefing_section_id LEFT JOIN briefing_answer a ON a.briefing_question_id=q.id WHERE s.briefing_id=? AND s.ativa=1 AND q.ativa=1 AND q.obrigatoria=1 AND (a.id IS NULL OR (a.nao_aplica=0 AND a.valor_json IS NULL))",'i',[$briefingId]);if($missing>0)briefing_json(['ok'=>false,'message'=>"Ainda há {$missing} pergunta(s) obrigatória(s) sem resposta."],422);
        $briefing=briefing_fetch($conn,$briefingId,true);$conn->begin_transaction();briefing_stmt($conn,'UPDATE briefing_answer_edit_session SET fechado_em=UTC_TIMESTAMP() WHERE participant_id=? AND fechado_em IS NULL','i',[$participantId])->close();briefing_snapshot($conn,$briefingId,'ENVIADO','PARTICIPANTE',$participantId);if((int)$briefing['exige_conferencia_interna']){$status='EM_CONFERENCIA';briefing_stmt($conn,"UPDATE briefing_online SET status=?,enviado_em=UTC_TIMESTAMP() WHERE id=?",'si',[$status,$briefingId])->close();briefing_event($conn,$briefingId,'briefing.client_submitted','PARTICIPANTE',$participantId);$logs=[];flow_connect_publish_operational_pending($conn,'briefing','client_response','resolvida','briefing',$briefingId,['titulo'=>$briefing['titulo'],'obra_id'=>(int)$briefing['obra_id'],'due_at'=>$briefing['prazo_em'],'responsavel_id'=>(int)($briefing['revisor_colaborador_id']??0)],null,$logs);briefing_flow_event($conn,$briefing,'client_submitted',null);}
        else {$status='APROVADO';briefing_stmt($conn,"UPDATE briefing_online SET status='APROVADO',enviado_em=UTC_TIMESTAMP(),aprovado_em=UTC_TIMESTAMP() WHERE id=?",'i',[$briefingId])->close();briefing_snapshot($conn,$briefingId,'APROVADO','SISTEMA',null);briefing_event($conn,$briefingId,'briefing.auto_approved','SISTEMA',null);$logs=[];flow_connect_publish_operational_pending($conn,'briefing','client_response','resolvida','briefing',$briefingId,['titulo'=>$briefing['titulo'],'obra_id'=>(int)$briefing['obra_id'],'due_at'=>$briefing['prazo_em'],'responsavel_id'=>(int)($briefing['revisor_colaborador_id']??0)],null,$logs);briefing_flow_event($conn,$briefing,'approved',null);}
        $conn->commit();briefing_publish_realtime($briefingId,$status==='APROVADO'?'briefing.approved':'briefing.submitted',['status'=>$status]);briefing_json(['ok'=>true,'status'=>$status]);
    }
    if($action==='ws.ticket')briefing_json(['ok'=>true,'ticket'=>briefing_ws_ticket($briefingId,$participantId,'CLIENTE')]);
    briefing_json(['ok'=>false,'message'=>'Ação desconhecida.'],400);
}catch(InvalidArgumentException $e){if($conn->errno)$conn->rollback();briefing_json(['ok'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){if($conn->errno)$conn->rollback();error_log('[Briefing external api] '.$e->getMessage());briefing_json(['ok'=>false,'message'=>'Não foi possível concluir a operação.'],500);}
