(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const root = location.pathname.split("/Fotografico")[0] || "/ImproovWeb";
  const state = { plans: [], plan: null, collaborators: [], selectedPin: null, csrf: "", saving: 0 };
  let planBroadcast = null;
  try { if (typeof BroadcastChannel !== "undefined") { planBroadcast = new BroadcastChannel("improov-fotografico"); planBroadcast.onmessage = event => window.dispatchEvent(new CustomEvent("improov:fotograficoUpdated", { detail: event.data || {} })); } } catch (_) { planBroadcast = null; }
  const broadcastPlanUpdate = (data) => { try { planBroadcast?.postMessage(data); } catch (_) {} };
  const periods = [["DIURNO", "Diurno"], ["GOLDEN_HOUR", "Golden Hour"], ["BLUE_HOUR", "Blue Hour"], ["NOTURNO", "Noturno"]];
  let images = [];
  const labels = { PLANO_A_FAZER: "Plano a fazer", EM_ELABORACAO: "Em elaboração", PRONTO_EXECUCAO: "Pronto para execução", EM_CONFERENCIA: "Em conferência", CONCLUIDO: "Concluído", HOLD: "Em HOLD", CANCELADO: "Cancelado" };
  const value = (v) => v == null || v === "" ? "—" : String(v);
  const esc = (v) => { const e = document.createElement("span"); e.textContent = value(v); return e.innerHTML; };
  const when = (v, time = false) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", ...(time ? { timeStyle: "short" } : {}) }).format(new Date(String(v).replace(" ", "T"))) : "—";
  const eventId = () => `foto-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
  function notice(message, error = false) { const box = $("fotoMessage"); box.textContent = message; box.hidden = false; box.classList.toggle("is-error", error); clearTimeout(notice.timer); notice.timer = setTimeout(() => box.hidden = true, 5000); }
  async function api(action, { method = "GET", data = null } = {}) {
    const url = new URL(`${root}/Fotografico/api.php`, location.origin);
    url.searchParams.set("action", action);
    if (method === "GET" && data) Object.entries(data).forEach(([k, v]) => url.searchParams.set(k, v));
    const options = { method, headers: {} }; let clientEventId = "";
    if (method !== "GET") { clientEventId = eventId(); options.headers = { "Content-Type": "application/json", "X-CSRF-Token": state.csrf }; options.body = JSON.stringify({ ...(data || {}), client_event_id: clientEventId }); state.lastEventId = clientEventId; }
    const response = await fetch(url, options); const body = await response.json().catch(() => null);
    if (!response.ok || !body?.success) { const error = new Error(body?.error?.message || "Não foi possível concluir a ação."); error.code = body?.error?.code; throw error; }
    if (method !== "GET") broadcastPlanUpdate({ plan_id: Number(body.data?.id || data?.plano_id || 0), event: "plan.updated", action, client_event_id: clientEventId });
    return body.data;
  }
  async function upload(type, entityId, file) { const form = new FormData(), clientEventId = eventId(); form.append("plano_id", state.plan.id); form.append("version", state.plan.lock_version); form.append("tipo", type); form.append("entidade_id", entityId); form.append("client_event_id", clientEventId); form.append("arquivo", file); const response = await fetch(`${root}/Fotografico/upload.php`, { method: "POST", headers: { "X-CSRF-Token": state.csrf }, body: form }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message || "Falha no upload."); broadcastPlanUpdate({ plan_id: Number(state.plan.id), event: "plan.updated", action: "upload", client_event_id: clientEventId }); return body.data; }
  const draftEditable = () => !!state.plan?.permissions?.edit && ["PLANO_A_FAZER", "EM_ELABORACAO", "PRONTO_EXECUCAO"].includes(state.plan.status) && activeVersion()?.status === "RASCUNHO";
  const activeVersion = () => state.plan?.versao_ativa;
  const mapPath = () => activeVersion()?.mapa_caminho ? `${root}/${activeVersion().mapa_caminho.replace(/^\//, "")}` : "";
  function applyPlan(plan, selected = state.selectedPin) { state.plan = plan; images = plan.imagens || []; state.csrf = plan.csrf_token || state.csrf; state.selectedPin = (plan.posicoes || []).some(p => String(p.id) === String(selected)) ? selected : null; render(); }
  async function loadCollaborators() { state.collaborators = (await api("collaborators")).colaboradores || []; }
  async function loadPlans() { const data = await api("list"); state.plans = data.planos || []; state.csrf = data.csrf_token || state.csrf; $("fotoNewCampaign").hidden = !data.can_manage; renderPlanList(); }
  async function loadPlan(id, selected) { applyPlan(await api("get", { data: { plano_id: id } }), selected); $("fotoListView").hidden = true; $("fotoDetailView").hidden = false; }
  function renderPlanList() { const q = $("fotoSearch").value.trim().toLowerCase(), filter = $("fotoStatusFilter").value, out = $("fotoPlanList"); out.replaceChildren(); const rows = state.plans.filter(p => (!filter || p.status === filter) && `${p.nome_obra} ${p.nomenclatura} ${p.responsavel_plano_nome || ""}`.toLowerCase().includes(q)); if (!rows.length) { out.innerHTML = '<div class="foto-card foto-muted">Nenhum plano fotográfico encontrado.</div>'; return; } rows.forEach(p => { const button = document.createElement("button"); button.className = "foto-plan-card"; button.innerHTML = `<header><span class="foto-status" data-status="${esc(p.status)}">${esc(labels[p.status] || p.status)}</span><small>Campanha ${p.campanha_numero}</small></header><h2>${esc(p.nomenclatura || p.nome_obra)}</h2><p>${esc(p.nome_obra)}</p><footer><small>${esc(p.responsavel_execucao_nome || "Sem executor")}</small><small>${p.pendencias_abertas || 0} pendências</small></footer>`; button.onclick = () => loadPlan(p.id).catch(e => notice(e.message, true)); out.append(button); }); }
  const stat = (label, v, detail = "") => `<div class="foto-stat"><small>${esc(label)}</small><strong>${esc(v)}</strong>${detail ? `<em>${esc(detail)}</em>` : ""}</div>`;
  const status = (s) => `<span class="foto-status" data-status="${esc(s)}">${esc(labels[s] || s)}</span>`;
  function render() { if (!state.plan) return; const p = state.plan; $("fotoCrumb").textContent = `Plano #PF-${String(p.id).padStart(4, "0")}`; $("fotoTitle").textContent = `Plano #PF-${String(p.id).padStart(4, "0")}`; $("fotoSubtitle").textContent = `Obra: ${p.nomenclatura || p.nome_obra} · Campanha ${p.campanha_numero}`; const st = $("fotoStatus"); st.textContent = labels[p.status] || p.status; st.dataset.status = p.status; $("fotoAddress").value = p.local || ""; $("fotoMapsUrl").value = p.obra_maps_url || ""; $("fotoPlannedDate").value = p.data_planejada || ""; $("fotoExecutor").replaceChildren(new Option("Selecione", ""), ...state.collaborators.map(c => new Option(c.nome, c.id))); $("fotoExecutor").value = p.responsavel_execucao_id || ""; $("fotoRevision").hidden = !p.permissions?.edit || !["PRONTO_EXECUCAO", "EM_CONFERENCIA"].includes(p.status); renderOverview(); renderMap(); renderPoints(); renderImages(); renderExecution(); renderIssues(); renderHistory(); }
  function renderOverview() { const p = state.plan, creation = (p.sla || []).find(x => x.tipo === "CRIACAO"), execution = (p.sla || []).find(x => x.tipo === "EXECUCAO"); $("fotoOverviewStats").innerHTML = stat("SLA criação", creation?.completed_at ? "Concluído" : when(creation?.due_at_effective), creation?.resultado || "Em andamento") + stat("Data de criação", when(p.created_at, true), p.responsavel_plano_nome || "Sem responsável") + stat("Previsão de execução", when(p.data_planejada), p.responsavel_execucao_nome || "Sem executor") + stat("Condição atual", labels[p.status] || p.status, p.holds?.find(h => !h.encerrado_em)?.codigo || "Sem HOLD"); const included = (p.imagens || []).filter(x => x.decisao === "INCLUIDA").length; $("fotoOverviewSummary").innerHTML = `<div class="foto-summary-item"><i class="fa-regular fa-image"></i><strong>${included}</strong><span>Imagens confirmadas</span></div><div class="foto-summary-item"><i class="fa-solid fa-location-dot"></i><strong>${(p.posicoes || []).length}</strong><span>Posições</span></div><div class="foto-summary-item"><i class="fa-regular fa-clock"></i><strong>${(p.posicoes || []).reduce((n, x) => n + (x.capturas || []).length, 0)}</strong><span>Períodos planejados</span></div>`; $("fotoSla").innerHTML = [creation, execution].filter(Boolean).map(s => `<div class="foto-sla-row"><span>SLA ${s.tipo.toLowerCase()}</span><small>${s.completed_at ? `Concluído ${when(s.completed_at, true)}` : `Vence ${when(s.due_at_effective, true)}`}</small></div>`).join(""); const ready = p.prontidao || { pronto: false, bloqueios: [] }; $("fotoReadiness").className = `foto-readiness${ready.pronto ? " is-ready" : ""}`; $("fotoReadiness").innerHTML = ready.pronto ? '<strong><i class="fa-solid fa-circle-check"></i> Plano completo e pronto para execução.</strong>' : `<strong><i class="fa-solid fa-triangle-exclamation"></i> O plano ainda não pode seguir para execução:</strong><ul>${(ready.bloqueios || []).map(b => `<li>${esc(b.mensagem)}</li>`).join("")}</ul>`; }
  function renderMap() { const image = $("fotoMapImage"), viewport = $("fotoMapViewport"), empty = $("fotoMapEmpty"), path = mapPath(); empty.hidden = !!path; viewport.hidden = !path; $("fotoMapZoom").hidden = !path; if (!path) return; if (image.src !== new URL(path, location.origin).href) { image.src = path; image.onload = () => renderMapPins(); } renderMapPins(); }
  function renderMapPins() { const layer = $("fotoPins"); layer.replaceChildren(); (state.plan.posicoes || []).forEach(pos => { const pin = document.createElement("button"); pin.type = "button"; pin.className = `foto-pin${String(pos.id) === String(state.selectedPin) ? " is-selected" : ""}`; pin.style.left = `${Number(pos.x_percentual)}%`; pin.style.top = `${Number(pos.y_percentual)}%`; pin.dataset.id = pos.id; pin.innerHTML = `<span>${esc(pos.codigo)}</span>`; let moving = false, moved = false; pin.addEventListener("pointerdown", e => { if (!draftEditable()) return; moving = true; moved = false; pin.setPointerCapture(e.pointerId); e.preventDefault(); }); pin.addEventListener("pointermove", e => { if (!moving) return; moved = true; placePin(pos, e); }); pin.addEventListener("pointerup", async e => { if (!moving) return; moving = false; placePin(pos, e); selectPin(pos.id); if (moved) await persistPin(pos, "Pin reposicionado."); }); pin.addEventListener("click", e => { e.stopPropagation(); selectPin(pos.id); }); layer.append(pin); }); }
  function pointFromEvent(event) { const image = $("fotoMapImage"), rect = image.getBoundingClientRect(); return { x_percentual: Math.max(0, Math.min(100, ((event.clientX - rect.left) / rect.width) * 100)), y_percentual: Math.max(0, Math.min(100, ((event.clientY - rect.top) / rect.height) * 100)) }; }
  function placePin(pos, event) { Object.assign(pos, pointFromEvent(event)); const pin = $("fotoPins").querySelector(`[data-id="${CSS.escape(String(pos.id))}"]`); if (pin) { pin.style.left = `${pos.x_percentual}%`; pin.style.top = `${pos.y_percentual}%`; } }
  function selectPin(id, scroll = true) { state.selectedPin = id; renderMapPins(); renderPoints(); if (scroll) { const pin = $("fotoPins").querySelector(`[data-id="${CSS.escape(String(id))}"]`); pin?.scrollIntoView({ behavior: "smooth", block: "center", inline: "center" }); requestAnimationFrame(() => document.querySelector(`[data-point-id="${CSS.escape(String(id))}"]`)?.scrollIntoView({ behavior: "smooth", block: "center" })); } }
  async function createPin(coords) { if (!draftEditable()) return; try { const next = await api("pin_create", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, versao_id: activeVersion().id, ...coords } }); applyPlan(next); state.selectedPin = next.posicoes?.at(-1)?.id || null; render(); notice("Ponto criado."); } catch (e) { notice(e.message, true); await loadPlan(state.plan.id); } }
  async function persistPin(pos, success) { if (!draftEditable()) return; try { const next = await api("pin_update", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, versao_id: activeVersion().id, pin_id: pos.id, x_percentual: pos.x_percentual, y_percentual: pos.y_percentual, observacao: pos.observacao || "", capturas: (pos.capturas || []).map(c => ({ periodo_codigo: c.periodo_codigo, prioridade: c.prioridade || 1, observacao: c.observacao || "", plano_imagem_ids: c.plano_imagem_ids || [] })) } }); applyPlan(next, pos.id); notice(success); } catch (e) { notice(e.message, true); await loadPlan(state.plan.id, pos.id); } }
  function renderPoints() { const points = state.plan.posicoes || [], images = state.plan.imagens || [], out = $("fotoPositionCards"); $("fotoPositionCount").textContent = `${points.length} posições · ${images.filter(i => i.decisao === "INCLUIDA" && !i.posicoes_vinculadas).length} imagens sem posição`; out.replaceChildren(); points.forEach(pos => { const open = String(pos.id) === String(state.selectedPin), item = document.createElement("article"); item.className = `foto-point${open ? " is-open" : ""}`; item.dataset.pointId = pos.id; const captureLabel = (pos.capturas || []).map(c => c.periodo_nome || periods.find(p => p[0] === c.periodo_codigo)?.[1]).join(", ") || "Sem períodos"; item.innerHTML = `<button type="button" class="foto-point-summary"><span class="foto-point-code">${esc(pos.codigo)}</span><span><strong>${esc(pos.observacao || "Sem descrição")}</strong><small>${esc(captureLabel)}</small></span><i class="fa-solid fa-chevron-down"></i></button><div class="foto-point-editor"></div>`; item.querySelector(".foto-point-summary").onclick = () => selectPin(pos.id); if (open) renderPointEditor(item.querySelector(".foto-point-editor"), pos); out.append(item); }); if (!points.length) out.innerHTML = '<div class="foto-empty-small">Ainda não há pontos no mapa.</div>'; }
  function renderPointEditor(out, pos) { const editable = draftEditable(); const note = document.createElement("textarea"); note.rows = 3; note.placeholder = "Descrição/observação do ponto"; note.value = pos.observacao || ""; note.disabled = !editable; let noteTimer; note.addEventListener("input", () => { pos.observacao = note.value; clearTimeout(noteTimer); noteTimer = setTimeout(() => persistPin(pos, "Descrição atualizada."), 550); }); out.append(note); periods.forEach(([code, label]) => { const capture = (pos.capturas || []).find(c => c.periodo_codigo === code); const row = document.createElement("div"); row.className = "foto-period-row"; row.innerHTML = `<header><label class="foto-check"><input type="checkbox" ${capture ? "checked" : ""} ${editable ? "" : "disabled"}> ${label}</label><select ${editable ? "" : "disabled"}><option value="1">Prioridade 1</option><option value="2">Prioridade 2</option><option value="3">Prioridade 3</option></select></header><div class="foto-period-images"></div>`; const enabled = row.querySelector("input"), priority = row.querySelector("select"), list = row.querySelector(".foto-period-images"); priority.value = capture?.prioridade || 1; images.filter(i => i.decisao === "INCLUIDA").forEach(image => { const check = document.createElement("label"); check.className = "foto-check"; const checked = (capture?.plano_imagem_ids || []).map(Number).includes(Number(image.id)); check.innerHTML = `<input type="checkbox" value="${image.id}" ${checked ? "checked" : ""} ${editable ? "" : "disabled"}> ${esc(image.imagem_nome)}`; check.querySelector("input").addEventListener("change", e => { if (e.target.checked && linkedInAnotherPoint(image.id, pos.id, code) && !confirm(`A imagem “${image.imagem_nome}” já está vinculada a outro ponto/período. Deseja reutilizá-la?`)) { e.target.checked = false; return; } syncCapture(pos, code, label, enabled, priority, list); }); list.append(check); }); const sync = () => syncCapture(pos, code, label, enabled, priority, list); enabled.addEventListener("change", sync); priority.addEventListener("change", sync); out.append(row); }); const footer = document.createElement("div"); footer.className = "foto-point-actions"; footer.innerHTML = '<button type="button" class="foto-text-btn">Localizar no mapa</button><button type="button" class="foto-text-btn foto-danger-text">Excluir ponto</button>'; const [locate, remove] = footer.querySelectorAll("button"); locate.onclick = () => selectPin(pos.id); remove.disabled = !editable; remove.onclick = () => removePin(pos); out.append(footer); }
  function linkedInAnotherPoint(imageId, pointId, period) { return (state.plan.posicoes || []).some(pos => String(pos.id) !== String(pointId) && (pos.capturas || []).some(c => c.periodo_codigo === period && (c.plano_imagem_ids || []).map(Number).includes(Number(imageId)))); }
  function syncCapture(pos, code, label, enabled, priority, list) { const index = (pos.capturas || []).findIndex(c => c.periodo_codigo === code); if (!enabled.checked) { if (index >= 0) pos.capturas.splice(index, 1); } else { const capture = { ...(index >= 0 ? pos.capturas[index] : {}), periodo_codigo: code, periodo_nome: label, prioridade: Number(priority.value), plano_imagem_ids: [...list.querySelectorAll("input:checked")].map(x => Number(x.value)) }; if (index >= 0) pos.capturas[index] = capture; else (pos.capturas ||= []).push(capture); } persistPin(pos, "Capturas atualizadas."); }
  async function removePin(pos) { const linked = (pos.capturas || []).some(c => (c.plano_imagem_ids || []).length); if (linked && !confirm("Este ponto possui imagens vinculadas. Deseja excluí-lo?")) return; try { const next = await api("pin_delete", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, versao_id: activeVersion().id, pin_id: pos.id, confirmar_exclusao: linked } }); applyPlan(next); notice("Ponto excluído."); } catch (e) { notice(e.message, true); } }
  function renderImages() { const out = $("fotoImages"); out.replaceChildren(); (state.plan.imagens || []).forEach(image => { const row = document.createElement("div"); row.className = "foto-image-row"; row.innerHTML = `<div class="foto-image-name"><strong>${esc(image.imagem_nome)}</strong><small>${esc(image.tipo_imagem || "Sem tipo")} · Referência: ${esc(image.referencia_nome || image.pavimento_referencia || "Sem referência")}</small></div><select><option value="PENDENTE">Pendente</option><option value="INCLUIDA">Confirmada</option><option value="EXCLUIDA">Excluir</option></select><span>${esc(image.periodos_vinculados || "Sem período")}</span><span>${esc(image.prioridade_vinculada ? `P${image.prioridade_vinculada}` : "—")}</span><span>${esc(image.posicoes_vinculadas || "Sem posição")}</span>`; const select = row.querySelector("select"); select.value = image.decisao; select.disabled = !draftEditable(); select.onchange = async () => { let reason = image.motivo_exclusao || ""; if (select.value === "EXCLUIDA" && !reason) { reason = prompt("Motivo da exclusão:") || ""; if (!reason) { select.value = image.decisao; return; } } try { const next = await api("image_update", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, versao_id: activeVersion().id, imagem_plano_id: image.id, decisao: select.value, motivo_exclusao: reason } }); applyPlan(next, state.selectedPin); notice("Decisão da imagem atualizada."); } catch (e) { notice(e.message, true); await loadPlan(state.plan.id, state.selectedPin); } }; out.append(row); }); }
  function renderExecution() { const p = state.plan, last = p.resumo_execucao?.ultima_tentativa; $("fotoExecutionStats").innerHTML = stat("Status", labels[p.status] || p.status) + stat("Data planejada", when(p.data_planejada), p.responsavel_execucao_nome || "Sem executor") + stat("Tentativas", p.resumo_execucao?.tentativas || 0, last ? when(last.executado_em) : "Nenhuma") + stat("Última decisão", last?.decisao_conferencia || "Pendente", last?.conferente_nome || ""); $("fotoSubmitExecution").disabled = !(p.permissions?.execute && p.status === "PRONTO_EXECUCAO"); $("fotoReviewSubmit").disabled = !(p.permissions?.review && p.status === "EM_CONFERENCIA"); const out = $("fotoExecutions"); out.replaceChildren(); (p.execucoes || []).forEach(ex => { const row = document.createElement("div"); row.className = "foto-timeline-item"; row.innerHTML = `<div class="foto-timeline-icon"><i class="fa-solid fa-camera"></i></div><div><h3>Tentativa ${ex.tentativa} · ${esc(ex.decisao_conferencia || ex.resultado)}</h3><small>Executada ${when(ex.executado_em, true)} · enviada por ${esc(ex.enviado_por_nome || ex.responsavel_nome)}</small><a class="foto-exec-link" target="_blank" rel="noopener" href="${esc(ex.material_url || "#")}">${esc(ex.material_url || "Sem link")}</a><p>${esc(ex.observacao || "")}${ex.consideracao ? `\nConferência: ${esc(ex.consideracao)}` : ""}</p></div>`; out.append(row); }); if (!out.children.length) out.innerHTML = '<div class="foto-empty-small">Nenhuma tentativa registrada.</div>'; }
  function timeline(id, rows, icon) { const out = $(id); out.replaceChildren(); rows.forEach(row => { const item = document.createElement("div"); item.className = "foto-timeline-item"; item.innerHTML = `<div class="foto-timeline-icon"><i class="fa-solid ${icon}"></i></div><div><h3>${esc(row.titulo || row.codigo || row.tipo || "Evento")}</h3><small>${when(row.criado_em || row.aberto_em, true)} · ${esc(row.responsavel_nome || row.ator_nome || "")}</small><p>${esc(row.detalhes || "")}</p></div>`; out.append(item); }); if (!out.children.length) out.innerHTML = '<div class="foto-empty-small">Nenhum registro.</div>'; }
  function renderIssues() { const p = state.plan, open = (p.pendencias || []).filter(x => x.status === "ABERTA"), holds = p.holds || []; $("fotoIssueStats").innerHTML = stat("Pendências abertas", open.length) + stat("Itens em HOLD", holds.filter(x => !x.encerrado_em).length) + stat("Impacto no SLA", holds.some(x => !x.encerrado_em && Number(x.afeta_sla)) ? "Pausado" : "Sem pausa") + stat("SLA execução", (p.sla || []).find(x => x.tipo === "EXECUCAO")?.resultado || "Aguardando"); timeline("fotoIssues", open, "fa-circle-exclamation"); timeline("fotoHolds", holds, "fa-pause"); $("fotoOpenHold").hidden = !p.permissions?.manage; }
  function renderHistory() { timeline("fotoHistory", state.plan.eventos || [], "fa-clock-rotate-left"); }
  async function updatePlan(fields, success) { try { applyPlan(await api("plan_update", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, ...fields } }), state.selectedPin); notice(success); } catch (e) { notice(e.message, true); await loadPlan(state.plan.id, state.selectedPin); } }
  $("fotoRefresh").onclick = () => loadPlan(state.plan.id, state.selectedPin).catch(e => notice(e.message, true)); $("fotoBack").onclick = async () => { $("fotoDetailView").hidden = true; $("fotoListView").hidden = false; await loadPlans(); }; $("fotoSearch").oninput = renderPlanList; $("fotoStatusFilter").onchange = renderPlanList;
  document.querySelectorAll(".foto-tabs button").forEach(button => button.onclick = () => { document.querySelectorAll(".foto-tabs button").forEach(x => x.classList.toggle("is-active", x === button)); document.querySelectorAll(".foto-panel").forEach(x => x.classList.toggle("is-active", x.dataset.panel === button.dataset.tab)); });
  [["fotoAddress", "endereco"], ["fotoMapsUrl", "maps_url"], ["fotoPlannedDate", "data_planejada"]].forEach(([id, key]) => { $(id).addEventListener("change", () => updatePlan({ [key]: $(id).value.trim() }, "Dados do plano atualizados.")); }); $("fotoExecutor").onchange = () => updatePlan({ responsavel_execucao_id: Number($("fotoExecutor").value || 0) }, "Responsável atualizado.");
  $("fotoMapUpload").onclick = () => $("fotoMapFile").click(); $("fotoMapFile").onchange = async e => { const file = e.target.files?.[0]; if (!file || !activeVersion()) return; try { await upload("mapa", activeVersion().id, file); await loadPlan(state.plan.id); await updatePlan({}, "Mapa enviado e prontidão recalculada."); } catch (err) { notice(err.message, true); } e.target.value = ""; }; $("fotoMapZoom").onclick = () => $("fotoMapImage").requestFullscreen?.(); $("fotoMapImage").onclick = e => { if (draftEditable()) createPin(pointFromEvent(e)); }; $("fotoAddPosition").onclick = () => mapPath() ? createPin({ x_percentual: 50, y_percentual: 50 }) : notice("Envie a imagem do mapa antes de criar posições.", true);
  $("fotoRevision").onclick = () => { const reason = prompt("Motivo da revisão:"); if (reason !== null) action("create_revision", { motivo: reason || "Revisão do plano" }, "Revisão criada."); };
  async function action(name, fields, success) { try { applyPlan(await api(name, { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, ...fields } })); notice(success); } catch (e) { notice(e.message, true); } }
  $("fotoSubmitExecution").onclick = async () => { const executed = $("fotoExecutedAt").value, material = $("fotoMaterialUrl").value.trim(); if (!executed || !material) return notice("Informe data e link do Drive.", true); try { const next = await api("submit_execution", { method: "POST", data: { plano_id: state.plan.id, version: state.plan.lock_version, executado_em: executed.replace("T", " ") + ":00", material_url: material, observacao: $("fotoExecutionNote").value.trim() } }); applyPlan(next); const execution = next.execucoes?.[0]; for (const file of $("fotoEvidenceFiles").files || []) await upload("evidencia_execucao", execution.id, file); await loadPlan(next.id); notice("Tentativa enviada para conferência."); } catch (e) { notice(e.message, true); } };
  $("fotoReviewSubmit").onclick = () => { const decision = $("fotoReviewDecision").value, note = $("fotoReviewNote").value.trim(), execution = (state.plan.execucoes || []).find(x => x.resultado === "EM_CONFERENCIA"); if (!decision || !execution) return notice("Selecione a decisão e a tentativa pendente.", true); if (decision !== "APROVADO" && !note) return notice("Informe a consideração da conferência.", true); action("review", { execucao_id: Number(execution.id), decisao: decision, consideracao: note }, "Conferência registrada."); };
  $("fotoOpenHold").onclick = () => $("fotoHoldDialog").showModal(); $("fotoConfirmHold").onclick = () => { $("fotoHoldDialog").close(); action("hold_open", { codigo: $("fotoHoldCode").value, detalhes: $("fotoHoldDetails").value.trim() }, "HOLD aberto."); }; $("fotoNewCampaign").onclick = () => { const obra = Number(prompt("ID da obra para a nova campanha:")); if (obra) api("create_campaign", { method: "POST", data: { obra_id: obra } }).then(p => loadPlan(p.id)).catch(e => notice(e.message, true)); };
  window.addEventListener("improov:fotograficoUpdated", event => { const data = event.detail || {}; if (!state.plan || Number(data.plan_id) !== Number(state.plan.id) || data.client_event_id === state.lastEventId) return; clearTimeout(state.wsTimer); state.wsTimer = setTimeout(() => loadPlan(state.plan.id, state.selectedPin).then(() => notice("Plano atualizado por outro usuário.")).catch(() => {}), 180); });
  function connectRealtime() { if (window.improovUploadWS?.connect) { window.improovUploadWS.connect(); return; } const url = location.protocol === "https:" ? `wss://${location.hostname}/ws/` : `ws://${location.hostname}:8082`; try { const socket = new WebSocket(url); socket.addEventListener("message", event => { try { const message = JSON.parse(event.data); if (String(message?.channel || "").startsWith("fotografico:")) window.dispatchEvent(new CustomEvent("improov:fotograficoUpdated", { detail: message.payload || {} })); } catch (_) {} }); socket.addEventListener("close", () => setTimeout(connectRealtime, 2500)); socket.addEventListener("error", () => socket.close()); } catch (_) { setTimeout(connectRealtime, 2500); } }
  (async () => { try { await loadCollaborators(); await loadPlans(); const id = Number(window.FOTOGRAFICO_INITIAL?.planId || 0); if (id) await loadPlan(id); connectRealtime(); } catch (e) { notice(e.message, true); } })();
})();
