name: Generate Changelog

on:
  push:
    tags:
      - 'v*.*.*'  # Dispara o workflow quando um push é feito em uma tag de versão (ex: v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        npm install -g auto-changelog
        auto-changelog -p -o ./changelog/CHANGELOG.md

    - name: Commit and Push Changelog
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "🔖 Update CHANGELOG.md for $GITHUB_REF"
        git push
