name: Generate Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Garante que todas as tags e histórico sejam recuperados

    - name: Generate Changelog
      id: changelog
      run: |
        npm install -g auto-changelog
        auto-changelog -p -o ./CHANGELOG.md

    - name: Commit and Push Changelog
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "🔖 Update CHANGELOG.md for $GITHUB_REF"
        git push origin HEAD:main  # Certifique-se de usar o nome correto do seu branch principal
